name = "Bootstrap 5 Autocomplete"
description = "Provides autocomplete for Bootstrap 5 utility classes."
version = "1"
repository = "https://github.com/mfabing/zed_bootstrap5_snippets/"
author = "Michael Fabing"
